class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = '/home/gaoshang/det/DET/'    # Base directory for saving network checkpoints.
        self.tensorboard_dir = self.workspace_dir + '/tensorboard/SPM'    # Directory for tensorboard files.
        self.pretrained_networks = self.workspace_dir+'/pretrained_networks/'
        self.lasot_dir = ''
        self.got10kdepth_dir = '/ssd2/gaoshang/GOT-10k-depth/full_data/train_data'
        self.trackingnet_dir = ''
        self.coco_dir = ''
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = ''
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
        self.davis_dir = ''
        self.youtubevos_dir = ''
        self.cdtb_dir = ''
        self.depthtrack_dir = '/data1/gaoshang/DET-Dataset/'
        self.depthVOST_test = '/ssd2/gaoshang/DepthVOST_test/'
        # self.trackingnetdepth_dir = '/home/yan/Data4/Datasets/EstimatedDepth/TrackingNet/'
        self.lasotdepth_dir = '/data1/gaoshang/LaSOT/dataset/'
        self.cocodepth_dir = '/data1/gaoshang/RGB_Depth/COCO_densedepth/'
        # self.cocodepth_dir = '/home/yan/Data4/Datasets/EstimatedDepth/COCO/'
